### ISSUE TITLE
Get rid of warnings when installing the CLI

### ISSUE THREAD

**Issue by dyoder** [pandastrike/huxley#106]
We're getting warnings from dependencies:

```
npm WARN engine panda-config@1.0.0-alpha-02: wanted: {"node":"^0.11.14"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine coffee-script-redux@2.0.0-beta8: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
```

The first one is easy to fix, of course, since it's our own package. For the second, I'm assuming we're using `coffee-script-redux` to support CSON parsing? If so, perhaps we should just switch over to YAML?

**Comment by freeformflow** [comment]
@dyoder, I believe I have made the necessary changes to panda-config.  I've updated the version number.  Could you publish the master branch or grant me publishing authority, please?
