### ISSUE TITLE
503 for huxley profile create

### ISSUE THREAD

**Issue by dyoder** [pandastrike/huxley#108]
huxley profile create panda

```
Error:
 { message: 'Unable to create profile.',
  value: { [Error: Expected 200, got 503] context: { response: [Object], data: [Object] } } }
```

**Comment by dyoder** [comment]
Tried several different profile names and omitting the profile. Same result.

**Comment by freeformflow** [comment]
The 503 means the request was bounced off the load balancer we use for SSL termination.  Both containers were de-activated when I looked at them.  Docker reports they have been offline for 30 hours, though I'm not sure what caused it.  

I've re-established the server.  I also figured out how to setup an email alarm to myself if this ever happens again.  This issue should be resolved for now, so I am closing.
