### ISSUE TITLE
Upgrade Kick Server to Recognize Already-Set DNS Records 

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/huxley#11]
If the sidekick server is asked to set a DNS record, it should check to see if that record already exists as specified.  This would save time during iterations.  This would require a change to the pandastrike/panda-hook repository.

**Comment by PandaWhisperer** [comment]
When doing a POST to `kick.<name>.cluster:2000`, the kick server updates the Route53 zone files. This might take up to a minute. The server should detect whether a correct name and ip already exists and return immediately if that is the case.

This will shave off up to a minute of restart time when redeploying an app.

**Comment by PandaWhisperer** [comment]
This is pending #24

**Comment by PandaWhisperer** [comment]
Starting work on this because #24 is closed.
