### ISSUE TITLE
Copy over a templates directory in `huxly mixin node` for client's copy

### ISSUE THREAD

**Issue by peterlongnguyen** [pandastrike/huxley#14]

**Comment by dyoder** [comment]
What does this mean? Moving to Review for further clarification.

**Comment by freeformflow** [comment]
My understanding is that this is just part of Peter's node mixin.  There is a directory in the huxley-cli portion of the repository.  It gets copied into the user's directory.  This functionality has already been partially completed, but I wanted to wait until the Node mixin was more fully done before we closed this.
