### ISSUE TITLE
`panda cluster delete` should not tell me it's done if the cluster is still spinning down

### ISSUE THREAD

**Issue by PandaWhisperer** [pandastrike/huxley#21]
See https://github.com/pandastrike/panda-cluster/issues/27

**Comment by dyoder** [comment]
Isn't this just a question of making the success message more accurate for `cluster delete`? Like `delete in progress` or something. The commands shouldn't block. That's what `cluster describe` is for.

**Comment by freeformflow** [comment]
Alpha 01 provides a "deletion underway" type message now.  But until #45 is complete, there is no way to tell when it's done, short of looking at the AWS Console.

**Comment by freeformflow** [comment]
Because of the change to the "delete" message and the creation of issues #32 and #45, I'm going to close this issue.
