### ISSUE TITLE
Establish SSL for the Huxley API Server

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/huxley#30]
This is a priority for Alpha 02

Right now PandaStrike has an API server running at [huxley.pandastrike.com](http://huxley.pandastrike.com).  We need to place it (and possibly additional instances) behind an SSL terminated load balancer to provide encryption security.   Currently, communication with API server is passed in-the-clear.

**Comment by freeformflow** [comment]
@lancelakey, could you give us some support here, please?  Currently, we only have one instance running the Huxley API, but eventually, our setup will require multiple instances behind an ELB.  

Regardless, Dan suggested that it's easier to just start with an ELB, give AWS the cert and let it deal with SSL details.  (That was a lot of acronyms...  hmm).  Could you help us get SSL setup, please?

**Comment by lancelakey** [comment]
It sounds like the task will probably be to setup an ELB,  attach an SSL cert to the ELB, attach  instance(s) to it, @PandaPup can give you more details about the instances.

@PandaPup Sure. I think @vanga can do this. 

@vanga Can you and would you do this?

**Comment by vanga** [comment]
@PandaPup I can set this up, which AWS region do you want this ELB to be in(us-west-1?)

Which PORT does the api server listen on?
health check end point?

**Comment by freeformflow** [comment]
@vanga.  
- We are operating in us-west-1
- The server is currently listening to port 80.
- We don't have a health check endpoint setup, currently.  I'd be happy to add one at a port of your choosing.  I'd need to read a little more about what response AWS is looking for, but I should be able to have it ready by tomorrow night (PDT).

**Comment by freeformflow** [comment]
Btw, thank you @vanga and @lancelakey.

**Comment by vanga** [comment]
@PandaPup I have setup the ELB,
`huxley-api-server-859791553.us-west-1.elb.amazonaws.com`
you should update R53 to point huxley.pandastrike.com to above elb end point.
Also I have enabled elb to listen on both 80,443 ports for now, You might want to change this to make it listen only on 443, (Note: redirection of HTTP to HTTPS is not possible with ELB )

Also you might want to change the security group of the api server in future, Only ELB (Security Group ID: `amazon-elb/amazon-elb-sg` ) will need access to the api server, we don't need to have 80,443 open for all

cc @lancelakey

**Comment by vanga** [comment]
btw, I set up TCP health check, I guess this is fine for now, if there is a chance that api server may not be functional even though the port 80 is open, then we might need a health check end point.

**Comment by freeformflow** [comment]
Okay.  Thank you so much @vanga!!

**Comment by freeformflow** [comment]
This works, thanks again to @vanga and @lancelakey
