### ISSUE TITLE
Create bash script for polling the kick server + add wiki documentation for it

### ISSUE THREAD

**Issue by PandaWhisperer** [pandastrike/huxley#74]
As discussed with @PandaPup this morning. The kick server needs an example of how to poll it using just `curl` and bash scripting. This will be used as template for our `.service` files.

Also, create a wiki page for the kick server and add this documentation there.

**Comment by PandaWhisperer** [comment]
Here are the relevant updates to panda-kick (accidentally pushed without creating a PR):
- Documentation: https://github.com/pandastrike/panda-kick/commit/316e8666fdea9c5c5459f9782acb7f82ae539d7f
- Working example: https://github.com/pandastrike/panda-kick/commit/cff82c406b7378f02a25c358215069f07aa7171d

And the link to the documentation on the wiki: https://github.com/pandastrike/huxley/wiki/Kick-Server

**Comment by freeformflow** [comment]
Thank you @PandaWhisperer
