### ISSUE TITLE
May We Request to Raise the VPC Limit on  Our Account?

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/huxley#76]
@lancelakey, may we request an increase to our AWS account's limit on VPCs?  The limit is 5 per account.  The [documentation states that we may request an increase to this](http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_vpc), but it's not clear if there is a charge.

**Comment by lancelakey** [comment]
Yes we may. @vanga would you do the honors please

**Comment by freeformflow** [comment]
@vanga, did Amazon grant our request?

**Comment by vanga** [comment]
@PandaPup I am sorry, I lost this email before.

I will update this as soon as I can.

**Comment by lancelakey** [comment]
@PandaPup Why do we need more VPC's? What are they being used for? What might we expect in terms of the # of VPC's we need in the next year?

**Comment by vanga** [comment]
For US-WEST-2

> I’m happy to inform you that we've approved and processed your VPC limit increase request for the US West (Oregon) region. Your new limit is 500

For US-WEST-1

> I've received your limit increase request and I see that your On Demand instance limit needs to match your VPC limit.
> 
> At this time your On Demand instance limit is 200, therefore we can only increase your VPCs to 200.
> I’m happy to inform you that we've approved and processed your VPC Requested VPCs limit increase request for the US West (Northern California) region. Your new limit is 200.

I think this is fine for now, if we need more in future we can open a new case to increase the limits.

Closing this.

**Comment by freeformflow** [comment]
@vanga @lancelakey,  this is great news.  Huxley clusters for everyone! haha.

Thank you for making that request and handling Amazon.
