### ISSUE TITLE
Add Mixins that Include ELK Stack Components

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/huxley#8]
We should create mixins for Kibana and Elasticsearch.  Each would be in their own containers and be separate mixins, but they will often be used together.  They are also useful as an example of a multi-component app, like in the Huxley Flavor Example, [Mint](https://github.com/pandastrike/mint).  They are pretty self-contained, but we can prove they are wired together after making requests to the sidekick server and have something visual to show.

**Comment by PandaWhisperer** [comment]
Mint is now working as of [`cecea31`](https://github.com/pandastrike/mint/commit/cecea31826ec34e48e0b12b04b2cab30a2c3bea5).

**Comment by PandaWhisperer** [comment]
What are the next steps? Update the templates in panda-cluster? @PandaPup

**Comment by freeformflow** [comment]
@PandaWhisperer, I'm sorry there was something wacky with my email.  Yes, the next step is to construct a template compatible with MustachJS rendering.  The templates will actually be stored in the Huxley CLI code.  We want to keep the scope of panda-cluster and other panda-\* components narrow.

There isn't current a separate module for template handling, but that should be placed into the pipeline.  Eventually, as Huxley matures we'll probably have 10 - 15 mixins stored in the CLI.

**Comment by PandaWhisperer** [comment]
As discussed with @PandaPup, I'm closing this ticket out because work on Mint is finished. I'll create a new ticket for work on templatetizing it.
