### ISSUE TITLE
Create a Page in Wiki Describing Services

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/huxley#84]
Please create a page in the wiki, as a sub-section of Cluster Architecture, that describes services in general.  Most important in this description is the API schema that services use to report their status to the kick server.  There was a question earlier about the official enum values of a service's state.  This should be codified in the wiki, please.

**Comment by PandaWhisperer** [comment]
Actually, I believe the point of this was to document the /status endpoint.

I've added that to the [Kick Server's Wiki Page](https://github.com/pandastrike/huxley/wiki/Kick-Server#posting-a-status-update).

**Comment by PandaWhisperer** [comment]
Created a [Services Page](https://github.com/pandastrike/huxley/wiki/Services) on the wiki. Just sorta brain dumped what I know. 

@PandaPup when you have time, could you review this for accuracy? And note any topics to add or expand upon.

**Comment by freeformflow** [comment]
The initial draft has been submitted.
