### ISSUE TITLE
Gather Requirements for Deploying Redis with the Huxley API

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/huxley#87]
This is related to #86.  Please gather requirements for deploying a Docker container running Redis as part of the Huxley API.  The relevant files should be added to the `huxley-api` directory.  

It is perfectly acceptable if the Alpha 04 deployment requires manual interaction.  But, as part of our long term goals, we want to be able to automate the deployment of the Huxley API server, ideally _with Huxley_, which is deployment _Inception_, haha.

**Comment by PandaWhisperer** [comment]
I looks like we already have a `Dockerfile` for Redis huxley-cli: https://github.com/pandastrike/huxley/blob/master/huxley-cli/templates/redis/Dockerfile

Looks like it's based on https://github.com/dockerfile/redis. I'm going to test it and tag it as `pandastrike/redis` or `huxley/redis` so we reuse it easily.

**Comment by freeformflow** [comment]
One more requirement...   We'd like to enable persistent storage with our Redis container.  Even though Redis is running in a Docker container, we'd like to store data to a disk that persists after the container is spun-down.  This will be necessary to save data between deployments.

**Comment by PandaWhisperer** [comment]
Alright. I updated said `Dockerfile` (and the template) with a working version based on Arch Linux. As soon as @dyoder adds me to our organization on Docker Hub, I'm going to publish that container. 

The installation instructions will be pulling that image from Docker Hub and running it.

**Comment by PandaWhisperer** [comment]
Instructions for installing a containerized version of Huxley using Docker have been added to the Wiki: https://github.com/pandastrike/huxley/wiki/Huxley-API-Guide#using-docker

Still pending: upload images to Docker Hub. Still waiting for @dyoder to add me to our organization.

**Comment by PandaWhisperer** [comment]
In the meantime, I'll add instructions for building the containers manually.

**Comment by PandaWhisperer** [comment]
Alright, Wiki now contains information on building the docker images.

**Comment by PandaWhisperer** [comment]
This should have probably gone into the comments for #92
