### ISSUE TITLE
Add Interview Prompts to the CLI

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/huxley#9]
We need a go-to module that will provide a prompt on the command-line whenever Huxley detects that it doesn't have the context it needs to carry out a command.  After interviewing the user, it should store that configuration data where appropriate and then carry out the requested command.

**Comment by dyoder** [comment]
So did [this module](https://github.com/flatiron/prompt) not work?

**Comment by freeformflow** [comment]
Peter is using `prompt`.   I meant that we needed a piece of reusable code that provides a prompt to the user, asking provided questions.  I assumed this would be tucked into a separate file, then we could use that code as needed with a given Huxley subcommand.

**Comment by freeformflow** [comment]
This has been deployed in the refactored version of Alpha 02.  After writing up a "questions" object in a separate file, developers may call upon reusable functions in `src/interview.coffee` that wrap the library `prompt`.  Thank you for your work, @peterlnguyen
