### ISSUE TITLE
Implment Additional CLI Features

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/huxley#98]
@peterlnguyen, I know that you have several tickets regarding CLI commands.  This ticket is to cover generally what I'd like for you to complete.  
- Please parse Dan's documentation [here](https://github.com/pandastrike/panda-wiki/blob/master/projects/products/huxley/asynchronous-commands.md), [here](https://github.com/pandastrike/panda-wiki/blob/master/projects/products/huxley/introduction.md), and [here](https://github.com/pandastrike/panda-wiki/blob/master/projects/products/huxley/sketch.md).  
- Determine what you can commit to delivering by EOD Monday and implement.  
- Also, please include documentation for CLI commands, in general.  That includes both the wiki and the CLI tool `help` blurbs.

**Comment by dyoder** [comment]
When there are conflicts, prioritize by the most recent. For conflicts that
cannot be resolved that way, do not hesitate to ping me.
